// <auto-generated />
using System;
using Checkpoint6._2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Checkpoint6._2.Migrations
{
    [DbContext(typeof(SpaceContext))]
    [Migration("20190118132515_dfdffdf")]
    partial class dfdffdf
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Checkpoint6._2.RavioliOnboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpireDate");

                    b.Property<string>("Name");

                    b.Property<DateTime>("PackDate");

                    b.Property<int?>("SpaceshipId");

                    b.HasKey("Id");

                    b.HasIndex("SpaceshipId");

                    b.ToTable("RavioliOnBoard");
                });

            modelBuilder.Entity("Checkpoint6._2.Spaceship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("Checkpoint6._2.RavioliOnboard", b =>
                {
                    b.HasOne("Checkpoint6._2.Spaceship", "Spaceship")
                        .WithMany("RavioliOnboards")
                        .HasForeignKey("SpaceshipId");
                });
#pragma warning restore 612, 618
        }
    }
}
